title: Heavenly Irregularity Monitoring
description: Classified Research Archive
baseurl: "/himresearchdivision.github.io"
url: "https://draecarysse.github.io"

markdown: kramdown

collections:
  archives:
    output: true
    permalink: /archives/:name/
